### ISSUE TITLE
TypeError: Cannot read property 'authDirectUrl' of undefined

### ISSUE THREAD

**Issue by plbecker** [yapily/yapily-sdk-nodejs#2]
Hi,
I'm getting the error `TypeError: Cannot read property 'authDirectUrl' of undefined` when running any of the samples in the Examples folder. I defined the correct application id, secret and callback url in the constants file. The error occurs on this line: 
`redirectUrl = YapilyApi.Auth.authDirectUrl(constants.APPLICATION_ID,userUUID,institutionId,constants.CALLBACK_URL,"account")`. Any idea how I could fix this?
Yapily_Api version is 0.0.153, npm version 6.12.0 running on macOS Mojave

**Comment by cloudwheels** [comment]
+1 Same problem.
@Pr0duktiv did you solve this?

**Comment by plbecker** [comment]
Sadly not, we are using Tink instead of Yapily now. This library is not very well maintained.

**Comment by cloudwheels** [comment]
Thanks for the reply. I was looking this library after having problems
getting started with Tink!

**Comment by cloudwheels** [comment]
@yapily-deepa @yapily-dexter @yapily-gkatzioura Can you confirm whether this project is still active please?

**Comment by yapily-mofe** [comment]
Hey @cloudwheels, I have been working on updating the examples as we've updated the SDKs. I'll have some updated examples up shortly!

**Comment by cloudwheels** [comment]
Hi @yapily-mofe - thanks for the quick response - it seemed like rather too
much work has gone into this project for it to be dead! (However, it would
seem some users are getting this impression ^^^) I look forward to the
updates.

**Comment by yapily-mofe** [comment]
Hello @cloudwheels, I've now updated the examples in line with the latest version of the SDK!
